development:
  adapter: async

test:
  adapter: async

production:
  # TODO CHANGE IN ACTUAL PRODUCTION
  # adapter: redis
  # url: <%= ENV['REDISCLOUD_URL'] %>
  adapter: redis
  url: redis://localhost:6379/1
